import type { Metadata } from 'next'
import './assets/css/styles.scss'
import Header from './components/Header'

import { Roboto } from 'next/font/google'
import GlobalFooter from '@/globals/Footer/Component'
const roboto = Roboto({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: {lang},
}: Readonly<{
  children: React.ReactNode
  params: {
    lang: string
  }
}>) {
  return (
    <html lang={lang}>
      <body className={roboto.className}>
        <div className="wrapper">
          <Header />
          <div className="page">
            {children}
            {/* <footer className="site-footer">
              <span>&copy; 2025 Music Demo</span>
            </footer> */}
          </div>
          
        </div>
      </body>
    </html>
  )
}
